### ISSUE TITLE
Any chance of an executable version?

### ISSUE THREAD

**Issue by incansvl** [misel228/monpos#1]
Per the title, would you be able to make a compiled executable available for those of us who don't have MS development tools installed?

**Comment by misel228** [comment]
I just created a release and attached a zip file with the exe-file and their necessary companions. Let me know if it works for you. :)

**Comment by misel228** [comment]
I made it a regular and not a pre-view release so it shows up on the start page.

**Comment by incansvl** [comment]
Sorry for the delayed reply. Works as described (after a warning from MS Defender antivirus, which is odd as I'm rinning Kaspersky as my main security suite)

Thanks for the solution ;-)

**Comment by misel228** [comment]
Yeah, I didn't bother to create a signed executable which is why Windows complained.

I'm glad it worked, though. 😊
